{% set name = "radiant-mlhub" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/radiant_mlhub-{{ version }}.tar.gz
  sha256: 93cabc3c8e9ba343cdb3b0bfaec01bf7a36aae75704fabfe96c8bf5cab9fa899

build:
  number: 1
  noarch: python
  entry_points:
    - mlhub=radiant_mlhub.cli:mlhub
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - click >=7.1.2,<9.0.0
    - pydantic ~=1.9.2
    - pystac ~=1.4.0
    - python-dateutil ~=2.8.2
    - requests ~=2.27.0
    - shapely ~=1.8.0
    - tqdm ~=4.64.0
    - urllib3 ~=1.26.11

test:
  imports:
    - radiant_mlhub
    - test
  commands:
    - pip check
    - mlhub --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/radiantearth/radiant-mlhub
  summary: A Python client for Radiant MLHub
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://radiant-mlhub.readthedocs.io
  dev_url: https://github.com/radiantearth/radiant-mlhub

extra:
  recipe-maintainers:
    - guidorice
    - mirob9363
