{% set name = "radiant-mlhub" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radiant_mlhub-{{ version }}.tar.gz
  sha256: 4a3e4c301c5e74f282bbf77b7d65db5a1d6c2a4dc6d18637eff6e1228ca2eb9d

build:
  number: 0
  noarch: python
  entry_points:
    - mlhub=radiant_mlhub.cli:mlhub
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - click ~=7.1.2
    - pystac ==0.5.4
    - python >=3.6
    - requests ~=2.25.1
    - tqdm ~=4.56.0

test:
  imports:
    - radiant_mlhub
    - test
  commands:
    - pip check
    - mlhub --version
  requires:
    - pip

about:
  home: https://github.com/radiantearth/radiant-mlhub
  summary: A Python client for Radiant MLHub
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://radiant-mlhub.readthedocs.io
  dev_url: https://github.com/radiantearth/radiant-mlhub

extra:
  recipe-maintainers:
    - duckontheweb
