{% set name = "radiant-mlhub" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radiant_mlhub-{{ version }}.tar.gz
  sha256: 1d95475ec9d4cf460d5201425ba843523b1885a9384b9c1adb81a4a1088adb0f

build:
  number: 0
  noarch: python
  entry_points:
    - mlhub=radiant_mlhub.cli:mlhub
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - click >=7.1.2,<9.0.0
    - pydantic ~=1.9
    - pystac ~=1.4
    - python-dateutil ~=2.8
    - requests ~=2.27
    - shapely ~=1.8
    - tqdm ~=4.64

test:
  imports:
    - radiant_mlhub
    - test
  commands:
    - pip check
    - mlhub --version
  requires:
    - pip

about:
  home: https://github.com/radiantearth/radiant-mlhub
  summary: A Python client for Radiant MLHub
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://radiant-mlhub.readthedocs.io
  dev_url: https://github.com/radiantearth/radiant-mlhub

extra:
  recipe-maintainers:
    - guidorice
