{% set name = "radiant-mlhub" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radiant_mlhub-{{ version }}.tar.gz
  sha256: d310afce962508a44c60f5738fef164c50e78f76c3e85813653824b39a189ca3

build:
  number: 0
  noarch: python
  entry_points:
    - mlhub=radiant_mlhub.cli:mlhub
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - python >=3.8
    - click >=7.1.2,<9.0.0
    - pydantic ~=1.9.2
    - pystac ~=1.4.0
    - python-dateutil ~=2.8.2
    - requests ~=2.27.0
    - shapely ~=1.8.0
    - tqdm ~=4.64.0

test:
  imports:
    - radiant_mlhub
    - test
  commands:
    - pip check
    - mlhub --version
  requires:
    - pip

about:
  home: https://github.com/radiantearth/radiant-mlhub
  summary: A Python client for Radiant MLHub
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://radiant-mlhub.readthedocs.io
  dev_url: https://github.com/radiantearth/radiant-mlhub

extra:
  recipe-maintainers:
    - guidorice
    - mirob9363
